version: "3"
services:
  docker-dev-mode:
    image: gage-conditions
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    volumes:
       - gage-conditions-data:/home/rstudio/gage-conditions
    environment:
      - ROOT=TRUE
      - PASSWORD=mypass

volumes:
  gage-conditions-data:

